### ISSUE TITLE
If ctrl-clicked, MyQOnly's review links are opened in Container of currently-focused tab

### ISSUE THREAD

**Issue by dholbert** [mikeconley/myqonly#18]
STR:
 1. Open a Container Tab (by e.g. long-pressing the "+" icon on your tabs toolbar, if you're using Nightly, and picking "Banking")
 2. Be sure that container tab is your currently active tab.
 3. Click the MyQOnly icon on your toolbar.
 4. Ctrl-click (Cmd-click on Mac) one of the links for your pending reviews, assuming you've got some.
(Or middle-mousebutton-click, which has the same semantics on Linux at least.)

ACTUAL RESULTS:
The review page opens in a new tab in the background, and that tab is *in the same container as your currently active tab*, e.g. "Banking", which you can tell because:
 - It's got the colorful underline to indicate this
 - it doesn't have your login state (assuming your auth cookie is in your default container)

EXPECTED RESULTS:
New tab should be in the default container.

Note that I get expected results if I simply left-click the link (no keyboard modifiers), and I also get expected results if I shift-click the link (which opens a new window, whose sole tab is in the default container).  Only ctrl-click/middle-mousebutton-click have this problem.

**Comment by mikeconley** [comment]
Hey @dholbert - the latest version of MyQOnly I released today has the ability to accept a Phabricator API token, and use Conduit to try to get review counts instead of scraping the page in the default container. It also adds the ability to _choose_ which container to open the Phabricator dashboard in. This might (finally) give you what you need here, and prevent you from needing to have a Phabricator session in your default container. If you're still using MyQOnly (or willing to give it another shot), give it a whirl and let me know if that works for you!

**Comment by mikeconley** [comment]
(You'll need to go into Settings and provide a Phabricator API token)

**Comment by dholbert** [comment]
Hi @mikeconley!

I can still reproduce this bug, with the latest version (regardless of whether I've set my phabricator API token).

> prevent you from needing to have a Phabricator session in your default container.

To clarify: I actually *want* to open phabricator in my default container. :)  The problem here is that it's opening in whatever-container-my-currently-focused-tab-is-in (when I ctrl+click the link in the extension's menu-popup)

If I choose a particular container in the MyQOnly options (e.g. "Open the dashboard in `[Work]`"), then I do see that this selection is honored and I can't reproduce any trouble here.

However, if I choose "Open the dashboard in `[No container]`" (the default), then ctrl+clicking the link in the menu popup will match the container of my currently visible tab.

**Comment by dholbert** [comment]
Here's a screencast demonstrating the problem:
https://github.com/user-attachments/assets/21f9657a-d0a7-4ceb-bb63-fd8f4273aa2b
 
* First half of the video is fine - when viewing a no-container tab, phabricator opens in new no-container tab, as I expect (because I have "Open the dashboard in `[No container]`" selected).
* Second half of the video shows the issue -- when I'm viewing an Amazon tab **in my Shopping container**, and I open MyQOnly and Ctrl+Click a link in its menu-popup, phabricator opens in a new Shopping-container tab, which results in a 404 page because I'm not signed in to phabricator in that container.
